# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='hazard',
            field=models.CharField(choices=[('0', 'No hazard'), ('1', 'Fire hazard'), ('2', 'Chemical hazard')], max_length=1),
        ),
    ]
