# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Dock unique identifier')),
            ],
            options={
                'verbose_name': 'Dock',
                'verbose_name_plural': 'Docks',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[(1, 'Enqueue'), (2, 'Active Job'), (3, 'Job done | Dequeue')], max_length=1, verbose_name='Job status')),
                ('start_time', models.DateTimeField(verbose_name='Job start date and time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Job end date and time')),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock.Dock')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.Ship')),
            ],
            options={
                'verbose_name': 'Jobs',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
