# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_auto_20170122_2218'),
        ('dock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[(b'1', 'Enqueue'), (b'2', 'Active Job'), (b'3', 'Job done | Dequeue')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('dock', 'ship')]),
        ),
    ]
